spring:
  datasource:
   url:  jdbc:mysql://localhost:3306/website
   username: root
   password: root
   driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
   hibernate:
    ddl-auto: update
   show-sql: true
   generate-ddl: true
   
   
# image file related
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
        
project.image: E:/images